module.exports = {
  en: {
    title: 'Password managers are still the default. TofuPass is for the awkward moments.',
    description: 'Use your password manager for most passwords. Use TofuPass when a password needs to be read, typed, spoken, taught, printed, reset, or shared temporarily.',
    label: 'Why TofuPass exists',
    gapLabel: 'The gap',
    gapTitle: 'Random character passwords are excellent inside a manager.',
    gapCopy: [
      'They are less excellent when someone has to say them over the phone, type them into a router screen, write them on a classroom handout, enter them on a TV keyboard, or copy them from a ticket during a reset.',
      'That does not mean password managers are bad. It means real life has handoff moments. TofuPass is built for those moments.',
    ],
    useLabel: 'The use cases',
    useTitle: 'TofuPass is for human handoff work.',
    useCases: ['MSP and helpdesk resets', 'Passwords read over the phone', 'Temporary credentials', 'Classroom setup', 'Family tech support', 'Wi-Fi passwords', 'Router, IoT, and device logins', 'Demo credentials for developers'],
    useCopy: 'The shared pain is simple: the password needs to be strong enough to take seriously and readable enough that a real person can handle it without five rounds of "is that a zero or an O?"',
    middleLabel: 'The middle',
    middleTitle: 'Readable, random, privacy-first.',
    middleCopy: [
      'TofuPass aims for the practical middle: word-based passwords that are easier to communicate, still randomly generated, and created locally in your browser by the web generator.',
      'Soft is easiest to type and best for low-risk temporary uses. Firm is the recommended default for most handoffs. Extra Firm is the stronger option when the site accepts a longer password.',
    ],
    examplesLabel: 'Example readable passwords',
    quote: 'TofuPass creates secrets. It does not store them, sync them, autofill them, or turn into a vault.',
    honestLabel: 'The honest bit',
    honestTitle: 'It is not magic security.',
    honestCopy: [
      'Longer is better when a service accepts it. Unique passwords matter more than clever patterns. Password managers are still the right home for long-term secrets. And if a password has been shared, printed, read aloud, or pasted into a temporary workflow, treat it like something that should be changed when the handoff is done.',
      'That is the whole idea: make safer temporary and human-facing passwords easy enough that people actually use them.',
    ],
    cta: 'Generate a readable password',
    ctaHref: '/',
    secondaryPrefix: 'Need the flagship workflow?',
    secondaryLink: 'Read the helpdesk/MSP page',
    secondaryHref: '/for/helpdesk/',
  },
  es: {
    title: 'Los gestores de contraseñas siguen siendo la opción normal. TofuPass es para los momentos incómodos.',
    description: 'Usa tu gestor para la mayoría de contraseñas. Usa TofuPass cuando una contraseña se tiene que leer, escribir, decir, enseñar, imprimir, restablecer o compartir temporalmente.',
    label: 'Por qué existe TofuPass',
    gapLabel: 'El hueco',
    gapTitle: 'Las contraseñas de caracteres aleatorios son excelentes dentro de un gestor.',
    gapCopy: [
      'Son menos excelentes cuando alguien tiene que decirlas por teléfono, escribirlas en la pantalla de un router, ponerlas en una hoja de clase, introducirlas con un teclado de TV o copiarlas desde un ticket durante un restablecimiento.',
      'Eso no significa que los gestores de contraseñas sean malos. Significa que la vida real tiene momentos de entrega. TofuPass está hecho para esos momentos.',
    ],
    useLabel: 'Los casos de uso',
    useTitle: 'TofuPass es para entregas entre personas.',
    useCases: ['Restablecimientos de MSP y helpdesk', 'Contraseñas leídas por teléfono', 'Credenciales temporales', 'Configuración de clase', 'Soporte técnico familiar', 'Contraseñas de Wi-Fi', 'Inicios de sesión de router, IoT y dispositivos', 'Credenciales de demo para desarrolladores'],
    useCopy: 'El dolor compartido es simple: la contraseña debe ser lo bastante fuerte para tomarse en serio y lo bastante legible para que una persona pueda manejarla sin cinco rondas de “¿eso es un cero o una O?”.',
    middleLabel: 'El punto medio',
    middleTitle: 'Legible, aleatorio y privado primero.',
    middleCopy: [
      'TofuPass busca el punto medio práctico: contraseñas basadas en palabras que son más fáciles de comunicar, siguen siendo generadas al azar y se crean localmente en tu navegador con el generador web.',
      'Soft es la más fácil de escribir y sirve para usos temporales de bajo riesgo. Firm es la opción recomendada para la mayoría de entregas. Extra Firm es la opción más fuerte cuando el sitio acepta una contraseña más larga.',
    ],
    examplesLabel: 'Ejemplos de contraseñas legibles',
    quote: 'TofuPass crea secretos. No los guarda, sincroniza, autocompleta ni se convierte en una bóveda.',
    honestLabel: 'La parte honesta',
    honestTitle: 'No es seguridad mágica.',
    honestCopy: [
      'Más largo es mejor cuando un servicio lo permite. Las contraseñas únicas importan más que los patrones ingeniosos. Los gestores de contraseñas siguen siendo el lugar correcto para secretos de largo plazo. Y si una contraseña se compartió, imprimió, leyó en voz alta o pegó en un flujo temporal, trátala como algo que debe cambiarse cuando termine la entrega.',
      'Esa es toda la idea: hacer que las contraseñas temporales y pensadas para personas sean lo bastante fáciles para que la gente realmente las use.',
    ],
    cta: 'Generar una contraseña legible',
    ctaHref: '/es/',
    secondaryPrefix: '¿Necesitas el flujo principal?',
    secondaryLink: 'Lee la página de helpdesk/MSP',
    secondaryHref: '/es/for/helpdesk/',
  },
  pt: {
    title: 'Gerenciadores de senhas ainda são o padrão. TofuPass é para os momentos complicados.',
    description: 'Use seu gerenciador para a maioria das senhas. Use TofuPass quando uma senha precisa ser lida, digitada, falada, ensinada, impressa, redefinida ou compartilhada temporariamente.',
    label: 'Por que o TofuPass existe',
    gapLabel: 'A lacuna',
    gapTitle: 'Senhas de caracteres aleatórios são excelentes dentro de um gerenciador.',
    gapCopy: [
      'Elas são menos excelentes quando alguém precisa dizê-las por telefone, digitá-las em uma tela de roteador, escrevê-las em uma folha de aula, inseri-las no teclado de uma TV ou copiá-las de um chamado durante uma redefinição.',
      'Isso não significa que gerenciadores de senhas sejam ruins. Significa que a vida real tem momentos de entrega. O TofuPass foi criado para esses momentos.',
    ],
    useLabel: 'Os casos de uso',
    useTitle: 'TofuPass é para trabalho de entrega humana.',
    useCases: ['Redefinições de MSP e helpdesk', 'Senhas lidas por telefone', 'Credenciais temporárias', 'Configuração de sala de aula', 'Suporte técnico da família', 'Senhas de Wi-Fi', 'Logins de roteador, IoT e dispositivos', 'Credenciais de demo para desenvolvedores'],
    useCopy: 'A dor comum é simples: a senha precisa ser forte o bastante para ser levada a sério e legível o bastante para uma pessoa lidar com ela sem cinco rodadas de “isso é zero ou O?”.',
    middleLabel: 'O meio termo',
    middleTitle: 'Legível, aleatório e privado primeiro.',
    middleCopy: [
      'O TofuPass busca o meio termo prático: senhas baseadas em palavras, mais fáceis de comunicar, ainda geradas aleatoriamente e criadas localmente no navegador pelo gerador web.',
      'Soft é mais fácil de digitar e melhor para usos temporários de baixo risco. Firm é o padrão recomendado para a maioria das entregas. Extra Firm é a opção mais forte quando o site aceita uma senha mais longa.',
    ],
    examplesLabel: 'Exemplos de senhas legíveis',
    quote: 'TofuPass cria segredos. Ele não os armazena, sincroniza, preenche automaticamente nem vira um cofre.',
    honestLabel: 'A parte honesta',
    honestTitle: 'Não é segurança mágica.',
    honestCopy: [
      'Mais longo é melhor quando o serviço aceita. Senhas únicas importam mais do que padrões inteligentes. Gerenciadores de senhas ainda são o lugar certo para segredos de longo prazo. E se uma senha foi compartilhada, impressa, lida em voz alta ou colada em um fluxo temporário, trate-a como algo que deve ser trocado quando a entrega terminar.',
      'Essa é a ideia toda: tornar senhas temporárias e voltadas para pessoas seguras o bastante e fáceis o bastante para serem usadas de verdade.',
    ],
    cta: 'Gerar uma senha legível',
    ctaHref: '/pt/',
    secondaryPrefix: 'Precisa do fluxo principal?',
    secondaryLink: 'Leia a página de helpdesk/MSP',
    secondaryHref: '/pt/for/helpdesk/',
  },
  fr: {
    title: 'Les gestionnaires de mots de passe restent la base. TofuPass est là pour les moments compliqués.',
    description: 'Utilisez votre gestionnaire pour la plupart des mots de passe. Utilisez TofuPass quand un mot de passe doit être lu, saisi, prononcé, enseigné, imprimé, réinitialisé ou partagé temporairement.',
    label: 'Pourquoi TofuPass existe',
    gapLabel: 'Le manque',
    gapTitle: 'Les mots de passe à caractères aléatoires sont excellents dans un gestionnaire.',
    gapCopy: [
      'Ils le sont moins quand quelqu’un doit les dire au téléphone, les saisir sur l’écran d’un routeur, les écrire sur une fiche de classe, les entrer avec une télécommande ou les copier depuis un ticket pendant une réinitialisation.',
      'Cela ne veut pas dire que les gestionnaires de mots de passe sont mauvais. Cela veut dire que la vraie vie a des moments de transmission. TofuPass est fait pour ces moments.',
    ],
    useLabel: 'Les cas d’usage',
    useTitle: 'TofuPass est fait pour les transmissions humaines.',
    useCases: ['Réinitialisations MSP et helpdesk', 'Mots de passe lus au téléphone', 'Identifiants temporaires', 'Configuration de classe', 'Support technique familial', 'Mots de passe Wi-Fi', 'Connexions routeur, IoT et appareils', 'Identifiants de démonstration pour développeurs'],
    useCopy: 'La douleur commune est simple : le mot de passe doit être assez fort pour être sérieux et assez lisible pour qu’une vraie personne puisse le gérer sans cinq allers-retours sur “c’est un zéro ou un O ?”.',
    middleLabel: 'Le juste milieu',
    middleTitle: 'Lisible, aléatoire, privé d’abord.',
    middleCopy: [
      'TofuPass vise le juste milieu pratique : des mots de passe basés sur des mots, plus faciles à communiquer, toujours générés aléatoirement et créés localement dans votre navigateur par le générateur web.',
      'Soft est le plus facile à saisir et convient aux usages temporaires à faible risque. Firm est le choix recommandé pour la plupart des transmissions. Extra Firm est plus fort quand le site accepte un mot de passe plus long.',
    ],
    examplesLabel: 'Exemples de mots de passe lisibles',
    quote: 'TofuPass crée des secrets. Il ne les stocke pas, ne les synchronise pas, ne les remplit pas automatiquement et ne devient pas un coffre-fort.',
    honestLabel: 'La partie honnête',
    honestTitle: 'Ce n’est pas de la sécurité magique.',
    honestCopy: [
      'Plus long est meilleur quand un service l’accepte. Les mots de passe uniques comptent plus que les motifs astucieux. Les gestionnaires de mots de passe restent le bon endroit pour les secrets à long terme. Et si un mot de passe a été partagé, imprimé, lu à voix haute ou collé dans un flux temporaire, traitez-le comme quelque chose à changer une fois la transmission terminée.',
      'C’est toute l’idée : rendre les mots de passe temporaires et humains assez sûrs et assez simples pour que les gens les utilisent vraiment.',
    ],
    cta: 'Générer un mot de passe lisible',
    ctaHref: '/fr/',
    secondaryPrefix: 'Besoin du flux principal ?',
    secondaryLink: 'Lire la page helpdesk/MSP',
    secondaryHref: '/fr/for/helpdesk/',
  },
  de: {
    title: 'Passwortmanager bleiben der Standard. TofuPass ist für die unbequemen Momente.',
    description: 'Nutze deinen Passwortmanager für die meisten Passwörter. Nutze TofuPass, wenn ein Passwort gelesen, getippt, gesprochen, erklärt, gedruckt, zurückgesetzt oder vorübergehend geteilt werden muss.',
    label: 'Warum es TofuPass gibt',
    gapLabel: 'Die Lücke',
    gapTitle: 'Zufällige Zeichenpasswörter sind in einem Manager hervorragend.',
    gapCopy: [
      'Sie sind weniger hervorragend, wenn jemand sie am Telefon sagen, in einen Router-Bildschirm tippen, auf ein Arbeitsblatt schreiben, mit einer TV-Tastatur eingeben oder bei einem Reset aus einem Ticket kopieren muss.',
      'Das heißt nicht, dass Passwortmanager schlecht sind. Es heißt, dass das echte Leben Übergabemomente hat. TofuPass ist für diese Momente gebaut.',
    ],
    useLabel: 'Die Einsatzfälle',
    useTitle: 'TofuPass ist für menschliche Übergaben.',
    useCases: ['MSP- und Helpdesk-Resets', 'Passwörter am Telefon vorlesen', 'Temporäre Zugangsdaten', 'Klassenzimmer-Setup', 'Familien-Tech-Support', 'Wi-Fi-Passwörter', 'Router-, IoT- und Geräte-Logins', 'Demo-Zugangsdaten für Entwickler'],
    useCopy: 'Das gemeinsame Problem ist einfach: Das Passwort muss stark genug sein, um ernst genommen zu werden, und lesbar genug, damit ein echter Mensch es ohne fünf Runden “ist das eine Null oder ein O?” verwenden kann.',
    middleLabel: 'Die Mitte',
    middleTitle: 'Lesbar, zufällig, privat zuerst.',
    middleCopy: [
      'TofuPass zielt auf die praktische Mitte: wortbasierte Passwörter, die leichter zu kommunizieren sind, trotzdem zufällig erzeugt werden und vom Web-Generator lokal in deinem Browser entstehen.',
      'Soft ist am leichtesten zu tippen und am besten für temporäre Nutzungen mit geringem Risiko. Firm ist der empfohlene Standard für die meisten Übergaben. Extra Firm ist stärker, wenn die Seite ein längeres Passwort akzeptiert.',
    ],
    examplesLabel: 'Beispiele für lesbare Passwörter',
    quote: 'TofuPass erstellt Geheimnisse. Es speichert, synchronisiert und füllt sie nicht automatisch aus und wird nicht zu einem Tresor.',
    honestLabel: 'Der ehrliche Teil',
    honestTitle: 'Es ist keine magische Sicherheit.',
    honestCopy: [
      'Länger ist besser, wenn ein Dienst es akzeptiert. Einzigartige Passwörter sind wichtiger als clevere Muster. Passwortmanager bleiben der richtige Ort für langfristige Geheimnisse. Und wenn ein Passwort geteilt, gedruckt, laut vorgelesen oder in einen temporären Ablauf eingefügt wurde, behandle es als etwas, das nach der Übergabe geändert werden sollte.',
      'Das ist die ganze Idee: sicherere temporäre und menschennahe Passwörter so einfach machen, dass Menschen sie wirklich benutzen.',
    ],
    cta: 'Ein lesbares Passwort erzeugen',
    ctaHref: '/de/',
    secondaryPrefix: 'Brauchst du den wichtigsten Ablauf?',
    secondaryLink: 'Lies die Helpdesk/MSP-Seite',
    secondaryHref: '/de/for/helpdesk/',
  },
  ja: {
    title: 'パスワードマネージャーは今でも基本です。TofuPass は扱いにくい場面のためのものです。',
    description: 'ほとんどのパスワードにはパスワードマネージャーを使いましょう。パスワードを読んだり、入力したり、声に出したり、教えたり、印刷したり、リセットしたり、一時的に共有したりする必要があるときは TofuPass を使います。',
    label: 'TofuPass が存在する理由',
    gapLabel: 'すき間',
    gapTitle: 'ランダム文字のパスワードは、マネージャーの中ではとても優秀です。',
    gapCopy: [
      'ただし、電話で伝える、ルーター画面に入力する、授業プリントに書く、テレビのキーボードで入れる、リセット中にチケットからコピーする、といった場面では扱いにくくなります。',
      'これはパスワードマネージャーが悪いという意味ではありません。現実には受け渡しの場面があるということです。TofuPass はそのために作られています。',
    ],
    useLabel: '使いどころ',
    useTitle: 'TofuPass は人に渡す作業のためのものです。',
    useCases: ['MSP とヘルプデスクのリセット', '電話で読み上げるパスワード', '一時的な認証情報', '授業のセットアップ', '家族の技術サポート', 'Wi-Fi パスワード', 'ルーター、IoT、デバイスのログイン', '開発者向けデモ認証情報'],
    useCopy: '共通する悩みは単純です。パスワードは真剣に扱える強さがあり、同時に「それはゼロ？ O？」を何度も確認しなくて済むほど読みやすい必要があります。',
    middleLabel: 'ちょうどよい中間',
    middleTitle: '読みやすく、ランダムで、プライバシー優先。',
    middleCopy: [
      'TofuPass は実用的な中間を目指します。伝えやすい単語ベースのパスワードでありながら、ランダムに生成され、Web 生成機能ではブラウザ内でローカルに作成されます。',
      'Soft は最も入力しやすく、低リスクの一時利用に向いています。Firm はほとんどの受け渡しにおすすめです。Extra Firm は、サイトが長いパスワードを受け付ける場合のより強い選択肢です。',
    ],
    examplesLabel: '読みやすいパスワードの例',
    quote: 'TofuPass は秘密を作ります。保存、同期、自動入力はせず、保管庫にもなりません。',
    honestLabel: '正直な話',
    honestTitle: '魔法のセキュリティではありません。',
    honestCopy: [
      'サービスが受け付けるなら、長い方が有利です。賢いパターンより、アカウントごとに固有であることが大切です。長期的な秘密の保管場所は今でもパスワードマネージャーです。そして、共有、印刷、読み上げ、一時的な作業への貼り付けをしたパスワードは、受け渡し後に変更すべきものとして扱ってください。',
      '考え方はそれだけです。一時的で人が扱うパスワードを、実際に使われるくらい簡単で安全にすることです。',
    ],
    cta: '読みやすいパスワードを生成',
    ctaHref: '/ja/',
    secondaryPrefix: '代表的な流れが必要ですか？',
    secondaryLink: 'ヘルプデスク/MSP ページを読む',
    secondaryHref: '/ja/for/helpdesk/',
  },
  'zh-cn': {
    title: '密码管理器仍然是默认选择。TofuPass 是为那些尴尬时刻准备的。',
    description: '大多数密码请使用密码管理器。当密码需要被读出、输入、讲解、打印、重置或临时分享时，请使用 TofuPass。',
    label: 'TofuPass 为什么存在',
    gapLabel: '缺口',
    gapTitle: '随机字符密码放在管理器里非常好。',
    gapCopy: [
      '但当有人必须在电话里念出来、输入到路由器屏幕、写在课堂讲义上、用电视键盘输入，或在重置时从工单里复制时，它们就不那么好用了。',
      '这并不是说密码管理器不好。只是现实生活中有交接密码的时刻。TofuPass 就是为这些时刻而做的。',
    ],
    useLabel: '使用场景',
    useTitle: 'TofuPass 面向人与人之间的密码交接。',
    useCases: ['MSP 和 helpdesk 重置', '电话里读出的密码', '临时凭据', '课堂设置', '家庭技术支持', 'Wi-Fi 密码', '路由器、IoT 和设备登录', '开发者演示凭据'],
    useCopy: '共同的痛点很简单：密码必须足够强，值得认真对待，也必须足够易读，让真人可以处理，而不必反复确认“这是零还是 O？”。',
    middleLabel: '中间路线',
    middleTitle: '易读、随机、隐私优先。',
    middleCopy: [
      'TofuPass 追求实用的中间路线：基于词语的密码更容易沟通，同时仍然随机生成，并由网页生成器在你的浏览器本地创建。',
      'Soft 最容易输入，适合低风险临时用途。Firm 是大多数交接场景的推荐默认值。Extra Firm 在网站接受更长密码时更强。',
    ],
    examplesLabel: '易读密码示例',
    quote: 'TofuPass 创建秘密。它不会存储、同步、自动填充，也不会变成密码库。',
    honestLabel: '诚实说明',
    honestTitle: '它不是魔法安全。',
    honestCopy: [
      '当服务允许时，越长越好。唯一密码比聪明模式更重要。长期秘密仍然应该保存在密码管理器中。如果密码曾被分享、打印、朗读或粘贴到临时流程里，就应把它当作交接完成后需要更改的东西。',
      '这就是全部想法：让更安全的临时密码和面向真人的密码足够简单，使人们真的愿意使用。',
    ],
    cta: '生成易读密码',
    ctaHref: '/zh-cn/',
    secondaryPrefix: '需要旗舰流程？',
    secondaryLink: '阅读 helpdesk/MSP 页面',
    secondaryHref: '/zh-cn/for/helpdesk/',
  },
  ar: {
    title: 'مديرو كلمات المرور ما زالوا الخيار الأساسي. TofuPass مخصص للحظات المربكة.',
    description: 'استخدم مدير كلمات المرور لمعظم كلمات المرور. استخدم TofuPass عندما تحتاج كلمة المرور إلى القراءة أو الكتابة أو النطق أو التعليم أو الطباعة أو إعادة التعيين أو المشاركة مؤقتًا.',
    label: 'لماذا يوجد TofuPass',
    gapLabel: 'الفجوة',
    gapTitle: 'كلمات المرور العشوائية ممتازة داخل مدير كلمات المرور.',
    gapCopy: [
      'لكنها أقل مثالية عندما يحتاج شخص إلى قولها عبر الهاتف، أو كتابتها في شاشة راوتر، أو وضعها في ورقة صف، أو إدخالها على لوحة مفاتيح تلفاز، أو نسخها من تذكرة أثناء إعادة التعيين.',
      'هذا لا يعني أن مديري كلمات المرور سيئون. بل يعني أن الحياة الواقعية فيها لحظات تسليم. TofuPass صُمم لتلك اللحظات.',
    ],
    useLabel: 'حالات الاستخدام',
    useTitle: 'TofuPass مخصص لعمل تسليم كلمات المرور بين البشر.',
    useCases: ['إعادة تعيين MSP و helpdesk', 'كلمات مرور تُقرأ عبر الهاتف', 'بيانات اعتماد مؤقتة', 'إعداد الصف', 'الدعم التقني للعائلة', 'كلمات مرور Wi-Fi', 'تسجيلات دخول الراوتر و IoT والأجهزة', 'بيانات اعتماد تجريبية للمطورين'],
    useCopy: 'المشكلة المشتركة بسيطة: يجب أن تكون كلمة المرور قوية بما يكفي لأخذها بجدية ومقروءة بما يكفي ليتعامل معها شخص حقيقي من دون خمس جولات من “هل هذا صفر أم O؟”.',
    middleLabel: 'المنتصف',
    middleTitle: 'مقروء، عشوائي، والخصوصية أولًا.',
    middleCopy: [
      'يستهدف TofuPass المنتصف العملي: كلمات مرور مبنية على الكلمات وأسهل في التواصل، لكنها ما زالت تُولد عشوائيًا وتُنشأ محليًا في متصفحك بواسطة مولّد الويب.',
      'Soft هو الأسهل في الكتابة والأفضل للاستخدامات المؤقتة منخفضة المخاطر. Firm هو الخيار الافتراضي لمعظم عمليات التسليم. Extra Firm أقوى عندما يقبل الموقع كلمة مرور أطول.',
    ],
    examplesLabel: 'أمثلة على كلمات مرور مقروءة',
    quote: 'ينشئ TofuPass أسرارًا. لا يخزنها أو يزامنها أو يملؤها تلقائيًا ولا يتحول إلى خزنة.',
    honestLabel: 'الجزء الصريح',
    honestTitle: 'ليست حماية سحرية.',
    honestCopy: [
      'الأطول أفضل عندما تقبله الخدمة. تفرد كلمة المرور أهم من الأنماط الذكية. مديرو كلمات المرور ما زالوا المكان الصحيح للأسرار طويلة المدى. وإذا تمت مشاركة كلمة مرور أو طباعتها أو قراءتها بصوت عالٍ أو لصقها في مسار مؤقت، فتعامل معها كشيء يجب تغييره عند انتهاء التسليم.',
      'هذه هي الفكرة كلها: جعل كلمات المرور المؤقتة والموجهة للبشر آمنة بما يكفي وسهلة بما يكفي ليستخدمها الناس فعلًا.',
    ],
    cta: 'إنشاء كلمة مرور مقروءة',
    ctaHref: '/ar/',
    secondaryPrefix: 'هل تحتاج إلى المسار الرئيسي؟',
    secondaryLink: 'اقرأ صفحة helpdesk/MSP',
    secondaryHref: '/ar/for/helpdesk/',
  },
  id: {
    title: 'Pengelola sandi tetap menjadi pilihan utama. TofuPass dibuat untuk momen yang canggung.',
    description: 'Gunakan pengelola sandi untuk sebagian besar sandi. Gunakan TofuPass saat sandi perlu dibaca, diketik, diucapkan, diajarkan, dicetak, direset, atau dibagikan sementara.',
    label: 'Mengapa TofuPass ada',
    gapLabel: 'Celahnya',
    gapTitle: 'Sandi karakter acak sangat baik di dalam pengelola sandi.',
    gapCopy: [
      'Namun kurang baik ketika seseorang harus mengucapkannya lewat telepon, mengetiknya di layar router, menulisnya di lembar kelas, memasukkannya di keyboard TV, atau menyalinnya dari tiket saat reset.',
      'Itu bukan berarti pengelola sandi buruk. Artinya kehidupan nyata punya momen handoff. TofuPass dibuat untuk momen itu.',
    ],
    useLabel: 'Kasus penggunaan',
    useTitle: 'TofuPass dibuat untuk pekerjaan handoff manusia.',
    useCases: ['Reset MSP dan helpdesk', 'Sandi dibacakan lewat telepon', 'Kredensial sementara', 'Pengaturan kelas', 'Dukungan teknologi keluarga', 'Sandi Wi-Fi', 'Login router, IoT, dan perangkat', 'Kredensial demo untuk developer'],
    useCopy: 'Rasa sakitnya sederhana: sandi harus cukup kuat untuk dianggap serius dan cukup mudah dibaca agar orang sungguhan bisa menanganinya tanpa lima putaran “itu nol atau O?”.',
    middleLabel: 'Titik tengah',
    middleTitle: 'Mudah dibaca, acak, mengutamakan privasi.',
    middleCopy: [
      'TofuPass mengejar titik tengah yang praktis: sandi berbasis kata yang lebih mudah dikomunikasikan, tetap dibuat secara acak, dan dibuat lokal di browser Anda oleh generator web.',
      'Soft paling mudah diketik dan paling cocok untuk penggunaan sementara berisiko rendah. Firm adalah default yang direkomendasikan untuk kebanyakan handoff. Extra Firm lebih kuat saat situs menerima sandi yang lebih panjang.',
    ],
    examplesLabel: 'Contoh sandi yang mudah dibaca',
    quote: 'TofuPass membuat rahasia. Ia tidak menyimpan, menyinkronkan, mengisi otomatis, atau berubah menjadi vault.',
    honestLabel: 'Bagian jujurnya',
    honestTitle: 'Ini bukan keamanan ajaib.',
    honestCopy: [
      'Lebih panjang lebih baik saat layanan menerimanya. Sandi unik lebih penting daripada pola pintar. Pengelola sandi tetap menjadi rumah yang tepat untuk rahasia jangka panjang. Jika sandi pernah dibagikan, dicetak, dibacakan, atau ditempel ke alur sementara, perlakukan sebagai sesuatu yang harus diganti saat handoff selesai.',
      'Itulah seluruh idenya: membuat sandi sementara dan sandi yang berhadapan dengan manusia cukup aman dan cukup mudah agar benar-benar digunakan.',
    ],
    cta: 'Buat sandi yang mudah dibaca',
    ctaHref: '/id/',
    secondaryPrefix: 'Butuh alur utama?',
    secondaryLink: 'Baca halaman helpdesk/MSP',
    secondaryHref: '/id/for/helpdesk/',
  },
  hi: {
    title: 'Password managers अब भी default हैं। TofuPass उन असुविधाजनक पलों के लिए है।',
    description: 'अधिकांश passwords के लिए अपना password manager इस्तेमाल करें। TofuPass तब इस्तेमाल करें जब password को पढ़ना, टाइप करना, बोलना, सिखाना, प्रिंट करना, reset करना या अस्थायी रूप से साझा करना पड़े।',
    label: 'TofuPass क्यों मौजूद है',
    gapLabel: 'खाली जगह',
    gapTitle: 'Random character passwords manager के अंदर बहुत अच्छे होते हैं।',
    gapCopy: [
      'वे तब कम अच्छे होते हैं जब किसी को उन्हें फोन पर बोलना हो, router screen में टाइप करना हो, classroom handout पर लिखना हो, TV keyboard से डालना हो, या reset के दौरान ticket से copy करना हो।',
      'इसका मतलब यह नहीं कि password managers खराब हैं। इसका मतलब है कि असली जीवन में handoff moments होते हैं। TofuPass उन्हीं moments के लिए बना है।',
    ],
    useLabel: 'Use cases',
    useTitle: 'TofuPass इंसानों के handoff work के लिए है।',
    useCases: ['MSP और helpdesk resets', 'Phone पर पढ़े जाने वाले passwords', 'Temporary credentials', 'Classroom setup', 'Family tech support', 'Wi-Fi passwords', 'Router, IoT और device logins', 'Developers के लिए demo credentials'],
    useCopy: 'साझा समस्या सरल है: password इतना मजबूत होना चाहिए कि उसे गंभीरता से लिया जाए, और इतना पढ़ने योग्य कि कोई असली व्यक्ति “यह zero है या O?” पाँच बार पूछे बिना संभाल सके।',
    middleLabel: 'बीच का रास्ता',
    middleTitle: 'Readable, random, privacy-first.',
    middleCopy: [
      'TofuPass practical middle का लक्ष्य रखता है: word-based passwords जिन्हें communicate करना आसान है, जो फिर भी randomly generated हैं, और web generator द्वारा आपके browser में locally बनाए जाते हैं।',
      'Soft टाइप करने में सबसे आसान है और low-risk temporary uses के लिए best है। Firm अधिकांश handoffs के लिए recommended default है। Extra Firm तब stronger option है जब site longer password स्वीकार करती है।',
    ],
    examplesLabel: 'Readable password examples',
    quote: 'TofuPass secrets बनाता है। यह उन्हें store, sync, autofill नहीं करता और vault नहीं बनता।',
    honestLabel: 'ईमानदार हिस्सा',
    honestTitle: 'यह जादुई security नहीं है।',
    honestCopy: [
      'जब service स्वीकार करे तो लंबा बेहतर है। Unique passwords clever patterns से अधिक important हैं। Long-term secrets के लिए password managers अब भी सही घर हैं। और यदि password साझा, printed, read aloud, या temporary workflow में paste हुआ है, तो handoff पूरा होने पर उसे बदलने योग्य मानें।',
      'यही पूरी बात है: temporary और human-facing passwords को इतना आसान और सुरक्षित बनाना कि लोग सच में उन्हें इस्तेमाल करें।',
    ],
    cta: 'Readable password generate करें',
    ctaHref: '/hi/',
    secondaryPrefix: 'Flagship workflow चाहिए?',
    secondaryLink: 'Helpdesk/MSP page पढ़ें',
    secondaryHref: '/hi/for/helpdesk/',
  },
  ru: {
    title: 'Менеджеры паролей остаются основным вариантом. TofuPass нужен для неловких моментов.',
    description: 'Используйте менеджер паролей для большинства паролей. Используйте TofuPass, когда пароль нужно прочитать, ввести, произнести, объяснить, напечатать, сбросить или временно передать.',
    label: 'Зачем существует TofuPass',
    gapLabel: 'Пробел',
    gapTitle: 'Случайные символьные пароли превосходны внутри менеджера.',
    gapCopy: [
      'Они менее превосходны, когда кому-то нужно сказать их по телефону, ввести на экране роутера, записать в классной памятке, набрать на телевизионной клавиатуре или скопировать из тикета во время сброса.',
      'Это не значит, что менеджеры паролей плохие. Это значит, что в реальной жизни бывают моменты передачи. TofuPass создан для таких моментов.',
    ],
    useLabel: 'Сценарии',
    useTitle: 'TofuPass нужен для передачи паролей людям.',
    useCases: ['Сбросы MSP и helpdesk', 'Пароли, читаемые по телефону', 'Временные учетные данные', 'Настройка класса', 'Семейная техподдержка', 'Пароли Wi-Fi', 'Логины роутеров, IoT и устройств', 'Демо-учетные данные для разработчиков'],
    useCopy: 'Общая боль проста: пароль должен быть достаточно сильным, чтобы относиться к нему серьезно, и достаточно читаемым, чтобы реальный человек мог справиться с ним без пяти раундов “это ноль или O?”.',
    middleLabel: 'Середина',
    middleTitle: 'Читаемо, случайно, приватно.',
    middleCopy: [
      'TofuPass стремится к практичной середине: пароли на основе слов проще передавать, они все еще генерируются случайно и создаются локально в браузере веб-генератором.',
      'Soft проще всего вводить и лучше всего подходит для временных низкорисковых случаев. Firm — рекомендуемый стандарт для большинства передач. Extra Firm сильнее, когда сайт принимает более длинный пароль.',
    ],
    examplesLabel: 'Примеры читаемых паролей',
    quote: 'TofuPass создает секреты. Он не хранит, не синхронизирует, не автозаполняет их и не превращается в хранилище.',
    honestLabel: 'Честная часть',
    honestTitle: 'Это не магическая безопасность.',
    honestCopy: [
      'Длиннее лучше, когда сервис это принимает. Уникальные пароли важнее хитрых шаблонов. Менеджеры паролей все еще правильное место для долгосрочных секретов. Если пароль был передан, напечатан, прочитан вслух или вставлен во временный процесс, считайте, что его нужно сменить после завершения передачи.',
      'В этом вся идея: сделать временные и человеческие пароли достаточно безопасными и достаточно простыми, чтобы люди действительно ими пользовались.',
    ],
    cta: 'Создать читаемый пароль',
    ctaHref: '/ru/',
    secondaryPrefix: 'Нужен основной сценарий?',
    secondaryLink: 'Откройте страницу helpdesk/MSP',
    secondaryHref: '/ru/for/helpdesk/',
  },
};
